### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by tqosu** [zlngan/ASQuery#1]
Dear authors,

When do you plan to release the training and inference code? Thanks.

**Comment by zlngan** [comment]
Thank you for your attention to our paper. I will clear up the relevant code as soon as possible, and I will notify you on this page after updating the code.

**Comment by zlngan** [comment]
@tqosu Hello, I have uploaded the training and inference code of Assembly101 in here. 
链接：https://pan.baidu.com/s/1CHkL9GDllxNVcdaVzeyzsQ?pwd=8oo7 
提取码：8oo7
It should be noted that I processed the assembly101 dataset into the breakfast dataset format, but unfortunately the processing code cannot be found.

**Comment by tqosu** [comment]
I assume the processing code is straightforward to reimplement. Could you reimplement it and update the GitHub repository to make it complete?

**Comment by zlngan** [comment]
Since I don't have the original data of Assembly101(which is difficult to download) and I'm busy at other projects, I don't have a plan to reimplement this file recently. If you have any problems when reimplementing, feel free to reach out to me anytime.

**Comment by tqosu** [comment]
Sounds good. Thanks.
